# Generated by Django 6.0.2 on 2026-03-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del Plato/Producto')),
                ('descripcion_producto', models.TextField(blank=True, help_text='Descripción que aparecerá en el carrito de compras', null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen para mostrar en el punto de venta o página web', null=True, upload_to='productos/')),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio base al público', max_digits=10)),
                ('es_combo', models.BooleanField(default=False, help_text='Marcar si es un paquete que incluye varios sub-productos')),
                ('esta_disponible', models.BooleanField(default=True, verbose_name='¿Está en el menú actualmente?')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto_producto',
            },
        ),
    ]
