# Generated by Django 4.2.29 on 2026-03-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Sube una imagen desde tu dispositivo', null=True, upload_to='productos/'),
        ),
    ]
