# Generated by Django 6.0.2 on 2026-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='registro_movimiento_inicial',
            field=models.TextField(blank=True, help_text='Nota del movimiento o lote inicial asociado al alta del producto en carta', null=True),
        ),
    ]
