# Generated by Django 6.0.2 on 2026-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_entrega_bonos_lotes_movimiento_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_catalogo',
            field=models.CharField(blank=True, default='', help_text='Opcional. Ruta bajo static/ (ej. productos/perro-clasico.jpg). Se muestra en la tienda si no hay imagen subida a media.', max_length=255),
        ),
    ]
