# Generated by Django 4.2.30 on 2026-04-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_imagen_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='esta_habilitado',
            field=models.BooleanField(default=True, help_text='Control manual para mostrar/ocultar productos. Se deshabilita automáticamente si faltan insumos.', verbose_name='¿Está habilitado para venta?'),
        ),
    ]
