# Generated by Django 6.0.2 on 2026-03-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, help_text='Código del lote provisto por el proveedor o interno', max_length=50, null=True)),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada por Compra'), ('salida_venta', 'Salida por Venta'), ('salida_desperdicio', 'Salida por Desperdicio/Merma'), ('ajuste', 'Ajuste de Inventario')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Obligatorio para productos perecederos', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'movimiento_inventario_movimientoinventario',
            },
        ),
    ]
