# Generated by Django 6.0.2 on 2026-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimiento_inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('entrada', 'Entrada por Compra'), ('entrada_inicial', 'Entrada inicial (alta de insumo / stock inicial)'), ('salida_venta', 'Salida por Venta'), ('salida_desperdicio', 'Salida por Desperdicio/Merma'), ('ajuste', 'Ajuste de Inventario')], max_length=20),
        ),
    ]
