# Generated by Django 6.0.2 on 2026-03-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, help_text='Cantidad a descontar (ej: 0.5 si son 500g y el insumo está en KG)', max_digits=10)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Receta / Escandallo',
                'verbose_name_plural': 'Recetas / Escandallos',
                'db_table': 'receta_receta',
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
