sonar.projectKey=ShoriExpress2026
sonar.projectName=ShoriExpress2026

# Archivos que no deben analizarse
sonar.exclusions=**/shoriexpress/.env,**/.env,**/.env.example,**/staticfiles/**,**/.venv/**,**/__pycache__/**,**/testing_helpers.py,**/demo_credentials.py

# Tests: credenciales ficticias, no producción
sonar.test.inclusions=**/tests.py,**/test_*.py,**/*_tests.py
sonar.issue.ignore.multicriteria=e1,e2
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=**/cuentas/tests.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=**/testing_helpers.py
