# Generated by Django 6.0.2 on 2026-03-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metodo_pago', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('puntos_ganados', models.PositiveIntegerField(default=0)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='metodo_pago.metodopago')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recibo', to='pedido.pedido')),
            ],
            options={
                'verbose_name': 'Recibo / Factura',
                'verbose_name_plural': 'Recibos / Facturas',
                'db_table': 'recibo_recibo',
            },
        ),
    ]
