# Generated by Django 6.0.2 on 2026-03-27 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('tipo_pedido', models.CharField(choices=[('local', 'Para comer aquí'), ('llevar', 'Para llevar'), ('domicilio', 'Domicilio')], default='local', max_length=20)),
                ('direccion_pedido', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_pedido', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En Preparación'), ('listo', 'Listo para Entrega'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'pedido_pedido',
            },
        ),
    ]
