# Generated by Django 6.0.2 on 2026-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega_estimada',
            field=models.DateTimeField(blank=True, help_text='Calculada al confirmar el pago (ej. hora actual + minutos de preparación)', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_entrega_real',
            field=models.DateTimeField(blank=True, help_text='Se registra automáticamente al marcar el pedido como entregado', null=True),
        ),
    ]
