# Generated by Django 4.2.30 on 2026-04-24 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_entrega_bonos_lotes_movimiento_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='descuento_bonos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='usar_bonos',
            field=models.BooleanField(default=False),
        ),
    ]
