# Generated by Django 4.2.30 on 2026-05-12 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20260423_2151'),
        ('pedido', '0003_pedido_descuento_bonos_pedido_usar_bonos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='usuario.usuario'),
        ),
    ]
