# Generated by Django 4.2.30 on 2026-06-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='instrucciones_pedido',
            field=models.TextField(blank=True, help_text="Instrucciones para la preparación del pedido, por ejemplo 'sin cebolla'", max_length=250, null=True),
        ),
    ]
