# Generated by Django 6.0.2 on 2026-04-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bonos_fidelidad',
            field=models.PositiveIntegerField(default=0, help_text='Bonos ganados (ej. compras iguales o superiores al umbral configurado)'),
        ),
    ]
