# Generated by Django 4.2.30 on 2026-04-24 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_entrega_bonos_lotes_movimiento_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion_password',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Fecha de última actualización de contraseña'),
            preserve_default=False,
        ),
    ]
