# Generated by Django 4.2.30 on 2026-04-24 02:51

from django.db import migrations


def cap_bonos_fidelidad(apps, schema_editor):
    Usuario = apps.get_model('usuario', 'Usuario')
    Usuario.objects.filter(bonos_fidelidad__gt=10).update(bonos_fidelidad=10)


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_ultima_actualizacion_password'),
    ]

    operations = [
        migrations.RunPython(cap_bonos_fidelidad),
    ]
