# Generated by Django 6.0.2 on 2026-03-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_insumo', models.CharField(max_length=100)),
                ('categoria_insumo', models.CharField(max_length=50)),
                ('unidad_medida', models.CharField(choices=[('GR', 'Gramos'), ('KG', 'Kilogramos'), ('ML', 'Mililitros'), ('LT', 'Litros'), ('UN', 'Unidad')], default='GR', max_length=10)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, help_text='Alerta cuando el stock baje de este valor', max_digits=10)),
                ('stock_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_compra_referencia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('estado_insumo', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('pocos', 'Pocas Unidades')], default='disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Insumo de Inventario',
                'verbose_name_plural': 'Insumos de Inventario',
                'db_table': 'inventario_inventario',
            },
        ),
    ]
