# Generated by Django 6.0.2 on 2026-04-09 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventario.inventario')),
            ],
            options={
                'verbose_name': 'Lote de inventario',
                'verbose_name_plural': 'Lotes de inventario',
                'db_table': 'inventario_inventariolote',
                'unique_together': {('insumo', 'codigo_lote')},
            },
        ),
    ]
