"""
Django settings for shoriexpress project.

Generated by 'django-admin startproject' using Django 4.2.29.
"""

import importlib
import os
import sys
from copy import copy
from pathlib import Path


# Compatibilidad con Python 3.14: Django 4.2 usa un copy() del Context que falla
# en este intérprete. Aplicamos un parche mínimo al iniciar la app.
try:
    from django.template import context as django_context
except Exception:  # pragma: no cover
    django_context = None
else:
    if getattr(django_context.BaseContext, '__copy__', None) is not None:
        def _compat_basecontext_copy(self):
            duplicate = self.__class__.__new__(self.__class__)
            duplicate.__dict__.update(self.__dict__)
            duplicate.dicts = self.dicts[:]
            if hasattr(self, 'render_context'):
                duplicate.render_context = copy(self.render_context)
            return duplicate

        django_context.BaseContext.__copy__ = _compat_basecontext_copy


def _load_env_file(path: Path) -> None:
    """Cargar variables desde .env sin sobrescribir valores ya existentes."""
    if not path.exists():
        return
    for raw_line in path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
_load_env_file(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# En producción: exporta DJANGO_SECRET_KEY y DJANGO_DEBUG=false
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("DJANGO_SECRET_KEY debe configurarse en el entorno o en .env.")

DEBUG = os.environ.get("DJANGO_DEBUG", "true").lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

# Render inyecta RENDER_EXTERNAL_HOSTNAME con la URL del servicio.
render_host = os.environ.get("RENDER_EXTERNAL_HOSTNAME", "").strip()
if render_host and render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_host)

# PythonAnywhere: define DJANGO_ALLOWED_HOSTS=tuusuario.pythonanywhere.com en el WSGI.
pa_domain = os.environ.get("PYTHONANYWHERE_DOMAIN", "").strip()
if pa_domain and pa_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(pa_domain)

# POST en HTTPS (PythonAnywhere, Render) requiere orígenes explícitos desde Django 4+.
_csrf_origins = []
for host in ALLOWED_HOSTS:
    if host and host != '*':
        _csrf_origins.append(f'https://{host}')
        if DEBUG:
            _csrf_origins.append(f'http://{host}')
for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(','):
    origin = origin.strip()
    if origin and origin not in _csrf_origins:
        _csrf_origins.append(origin)
CSRF_TRUSTED_ORIGINS = _csrf_origins
CSRF_FAILURE_VIEW = 'cuentas.views.csrf_failure'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rol',
    'usuario',
    'inventario',
    'producto',
    'receta',
    'movimiento_inventario',
    'pedido',
    'detalle_pedido',
    'metodo_pago',
    'recibo',
    'dashboard',
    'cuentas',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'shoriexpress.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cuentas.context_processors.user_context',
                'producto.context_processor.cart_total_amount',
            ],
        },
    },
]

WSGI_APPLICATION = 'shoriexpress.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# XAMPP: enciende MySQL en el panel; crea la BD `shori_express` en phpMyAdmin.
# Usa 127.0.0.1 (no "localhost") para forzar TCP y evitar problemas en Windows.
# Contraseña: MYSQL_PASSWORD en el entorno sobreescribe el valor por defecto (solo dev).

def _mysql_driver_available() -> bool:
    try:
        importlib.import_module("MySQLdb")
        return True
    except ModuleNotFoundError:
        try:
            pymysql = importlib.import_module("pymysql")
            pymysql.install_as_MySQLdb()
            importlib.import_module("MySQLdb")
            return True
        except Exception:
            return False


USE_SQLITE = os.environ.get("USE_SQLITE", "").strip().lower() in {"1", "true", "yes"}
if not USE_SQLITE and not _mysql_driver_available():
    USE_SQLITE = True

MYSQL_DEFAULTS = {
    "ENGINE": "django.db.backends.mysql",
    "NAME": os.environ.get("MYSQL_DATABASE", "shori_express"),
    "USER": os.environ.get("MYSQL_USER", "root"),
    "PASSWORD": os.environ.get("MYSQL_PASSWORD", ""),
    "HOST": os.environ.get("MYSQL_HOST", "127.0.0.1"),
    "PORT": os.environ.get("MYSQL_PORT", "3306"),
    "OPTIONS": {
        "charset": "utf8mb4",
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    },
}

if USE_SQLITE:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {"default": MYSQL_DEFAULTS}

# Use SQLite for tests
if 'test' in sys.argv:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.environ.get('DJANGO_TIME_ZONE', 'America/Bogota')

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Media files (uploads de imágenes, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# SEGURIDAD DE SESIÓN
# ============================================================
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 7200
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_NAME = 'shoriexpress_session'
SESSION_COOKIE_HTTPONLY = True

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'