# Generated by Django 4.2.30 on 2026-04-24 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('detalle_pedido', '0002_detallepedido_auditing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
