# Generated by Django 6.0.2 on 2026-03-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_metodo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'db_table': 'metodo_pago_metodopago',
            },
        ),
    ]
